# Generated by Django 3.2.6 on 2021-08-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
