# Generated by Django 3.2.6 on 2021-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
